In [2]:
import geopandas as gpd
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
import matplotlib.pyplot as plt
from shapely.geometry import LineString, Point
import json
import os

In [3]:
# paths
local_path = "/Volumes/samsung-4tb/b2p/impact-model/no_order_1_less_than_500m_with_top_sites/model_outputs/"
path_data_path = "joined_data/travel_paths_to_all_education_facilities_fixed.parquet"
output_folder_path ="/Volumes/samsung-4tb/b2p/impact-model/cleaned_data/"

et_path = os.path.join(local_path, "ethiopia/",path_data_path)
civ_path = os.path.join(local_path, "ivory_coast/",path_data_path)
kenya_path = os.path.join(local_path, "kenya/",path_data_path)
rwanda_path = os.path.join(local_path, "rwanda/",path_data_path)
tanzania_path = os.path.join(local_path, "tanzania/",path_data_path)
uganda_path = os.path.join(local_path, "uganda/",path_data_path)
zambia_path = os.path.join(local_path, "zambia/",path_data_path)

In [5]:
# read et_path as geopandas df

civ_path_df = pd.read_parquet(civ_path)
civ_path_df

,row,col,subregion,coords,exit_point_used,exit_point_index,destination_index,destination_coords,exit_point_index_path,h3_index,exit_point_path,path_to_exit_point,exit_point_used_no_sites,exit_point_path_no_sites,path_to_exit_point_no_sites
0,3653,1262,21093,"[-7.5474, 7.69195]","[-7.5474, 7.69195]",230524,2095,"[-7.47986, 7.6695]","[230524, 83597, 83598, 83599, 83600, 83601, 83...",8875a19995fffff,"[[-7.5474, 7.69195], [-7.5409, 7.69699], [-7.5...","[[-7.5474, 7.69195]]",None,None,None
1,4463,1478,27651,"[-7.3675, 7.016667]","[-7.3744, 7.01404]",83875,1485,"[-7.39222, 7.0519]","[83875, 82970, 82971, 82972, 82973]",8875a12459fffff,"[[-7.3744, 7.01404], [-7.40107, 7.04269], [-7....","[[-7.3675, 7.016667], [-7.3683333, 7.0158334],...",None,None,None
2,4464,1477,27651,"[-7.3683333, 7.0158334]","[-7.3744, 7.01404]",83875,1485,"[-7.39222, 7.0519]","[83875, 82970, 82971, 82972, 82973]",8875a12459fffff,"[[-7.3744, 7.01404], [-7.40107, 7.04269], [-7....","[[-7.3683333, 7.0158334], [-7.3683333, 7.01500...",None,None,None
3,4465,1477,27651,"[-7.3683333, 7.0150003]","[-7.3744, 7.01404]",83875,1485,"[-7.39222, 7.0519]","[83875, 82970, 82971, 82972, 82973]",8875a12459fffff,"[[-7.3744, 7.01404], [-7.40107, 7.04269], [-7....","[[-7.3683333, 7.0150003], [-7.3683333, 7.01416...",None,None,None
4,4466,1471,27651,"[-7.373462, 7.0139494]","[-7.3744, 7.01404]",83875,1485,"[-7.39222, 7.0519]","[83875, 82970, 82971, 82972, 82973]",8875a12451fffff,"[[-7.3744, 7.01404], [-7.40107, 7.04269], [-7....","[[-7.373462, 7.0139494], [-7.374401, 7.0140433...",None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4964078,6807,2094,45547,"[-6.8541665, 5.0633335]","[-6.85284, 5.06473]",104919,170,"[-6.61776, 5.16575]","[104919, 261139, 104917, 104918, 208015, 10492...",8875a96f0dfffff,"[[-6.85284, 5.06473], [-6.84043, 5.06062], [-6...","[[-6.8541665, 5.0633335], [-6.8533335, 5.06416...",None,"[[-6.86037, 5.05999], [-6.86074, 5.05988], [-6...","[[-6.8541665, 5.0633335], [-6.855, 5.0633335],..."
4964079,6808,2090,45547,"[-6.8575, 5.0625]","[-6.85284, 5.06473]",104919,170,"[-6.61776, 5.16575]","[104919, 261139, 104917, 104918, 208015, 10492...",8875a96f0dfffff,"[[-6.85284, 5.06473], [-6.84043, 5.06062], [-6...","[[-6.8575, 5.0625], [-6.8575, 5.0633335], [-6....",None,"[[-6.86037, 5.05999], [-6.86074, 5.05988], [-6...","[[-6.8575, 5.0625], [-6.858333, 5.061667], [-6..."
4964080,6809,2089,45547,"[-6.858333, 5.061667]","[-6.85284, 5.06473]",104919,170,"[-6.61776, 5.16575]","[104919, 261139, 104917, 104918, 208015, 10492...",8875a96f0dfffff,"[[-6.85284, 5.06473], [-6.84043, 5.06062], [-6...","[[-6.858333, 5.061667], [-6.8575, 5.0625], [-6...",None,"[[-6.86037, 5.05999], [-6.86074, 5.05988], [-6...","[[-6.858333, 5.061667], [-6.8591666, 5.0608335]]"
4964081,6810,2088,45547,"[-6.8591666, 5.0608335]","[-6.85284, 5.06473]",104919,170,"[-6.61776, 5.16575]","[104919, 261139, 104917, 104918, 208015, 10492...",8875a96f0dfffff,"[[-6.85284, 5.06473], [-6.84043, 5.06062], [-6...","[[-6.8591666, 5.0608335], [-6.858333, 5.061667...",None,"[[-6.86037, 5.05999], [-6.86074, 5.05988], [-6...","[[-6.8591666, 5.0608335]]"
4964082,6811,2087,45547,"[-6.86037, 5.05999]","[-6.86037, 5.05999]",115016,170,"[-6.61776, 5.16575]","[115016, 104919, 261139, 104917, 104918, 20801...",8875a96f05fffff,"[[-6.86037, 5.05999], [-6.85284, 5.06473], [-6...","[[-6.86037, 5.05999]]",None,None,None

In [8]:
civ_path_columns = civ_path_df.columns.tolist()
civ_path_columns

['row',
 'col',
 'subregion',
 'coords',
 'exit_point_used',
 'exit_point_index',
 'destination_index',
 'destination_coords',
 'exit_point_index_path',
 'h3_index',
 'exit_point_path',
 'path_to_exit_point',
 'exit_point_used_no_sites',
 'exit_point_path_no_sites',
 'path_to_exit_point_no_sites']

In [10]:
# create a new dataframe with only exit_point_path and h3_index columns
exit_point_paths = civ_path_df[['exit_point_path', 'h3_index']]

In [ ]:
# convert exit_point_path to a geodataframe with the exit_point_path as a line string geometry
exit_point_paths['geometry'] = exit_point_paths['exit_point_path'].apply(
    lambda x: LineString([Point(coord) for coord in json.loads(x)])
)

                                           exit_point_path         h3_index
0        [[-7.5474, 7.69195], [-7.5409, 7.69699], [-7.5...  8875a19995fffff
1        [[-7.3744, 7.01404], [-7.40107, 7.04269], [-7....  8875a12459fffff
2        [[-7.3744, 7.01404], [-7.40107, 7.04269], [-7....  8875a12459fffff
3        [[-7.3744, 7.01404], [-7.40107, 7.04269], [-7....  8875a12459fffff
4        [[-7.3744, 7.01404], [-7.40107, 7.04269], [-7....  8875a12451fffff
...                                                    ...              ...
4964078  [[-6.85284, 5.06473], [-6.84043, 5.06062], [-6...  8875a96f0dfffff
4964079  [[-6.85284, 5.06473], [-6.84043, 5.06062], [-6...  8875a96f0dfffff
4964080  [[-6.85284, 5.06473], [-6.84043, 5.06062], [-6...  8875a96f0dfffff
4964081  [[-6.85284, 5.06473], [-6.84043, 5.06062], [-6...  8875a96f0dfffff
4964082  [[-6.86037, 5.05999], [-6.85284, 5.06473], [-6...  8875a96f05fffff

[4964083 rows x 2 columns]